### ISSUE TITLE
Perf: Running compiler tests takes about twice as long as xunit.console.

### ISSUE THREAD

**Issue by Pilchie** [Pilchie/xunit.runner.wpf#14]

**Comment by Pilchie** [comment]
@jaredpar said he didn't notice a difference on VsVim tests though.

**Comment by jaredpar** [comment]
This may be fixed with #19.

**Comment by jaredpar** [comment]
This does appear to have been fixed with #19.  I ran a stop watch test against TDD.NET and xunit.runner.wpf against the VsVim unit tests.  The tests stretched across two assemblies and totaled 3929 total tests:

- TDD.NET: 51 seconds
- xunit.runner.wpf: 38 seconds

Can't test against Roslyn since we still have some issues with the xunit 2 PR.  But I think it's safe to close this issue now.  Can reopen if Roslyn does end up being slower.
